version: "3.8"

services:
    postgres:
      container_name: ${POSTGRES_CONTAINER_NAME}
      image: fiadotava/postgres
      restart: on-failure
      build:
        context: ./PostgreSQL/
        dockerfile: Dockerfile
      ports:
        - 5430:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - fiadotava_network

    node:
      container_name: fiadotava_node
      image: fiadotava/node
      restart: on-failure
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - ${API_PORT}:${API_PORT}
      environment:
        - POSTGRES_HOST=${POSTGRES_CONTAINER_NAME}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - API_HOST=${API_HOST}
      links:
        - postgres
      volumes:
        - ./:/usr/local/app/
        - /usr/src/app/node_modules
      depends_on:
        - postgres
      networks:
        - fiadotava_network

volumes:
  pgdata:

networks:
  fiadotava_network:
    driver: bridge
